services:
  app:
    build: .
    image: nirbeat/devops-app-usernode:latest
    ports:
      - "3000"
    env_file: .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/login
    depends_on:
      - mongo

    # # Se especifica que al levantar el compose, se hagan 3 copias del
    # # contenedor para balancear carga 
    deploy:
      replicas: 3 

    # #   -docker compose up -d --scale <nombre app>=<numero>
    # # Para hacerlo a mano desde CLI se especifica un service
    # #   -docker swarm init
    # #   -docker service create --name <nombre> --replicas <cantidad> -p <externo>:<interno> <imagen>
    # # Se puede escalar la cantidad mediante CLI
    # #   -docker service scale <nombre>=5
    
    restart: unless-stopped

  mongo:
    image: mongo:7
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
